volumes:
  prometheus_data: {}

services:
  app:
    build:
      context: .
    container_name: app
    ports:
      - "8000:8000"
    expose:
      - "8000"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    expose:
      - "9090"
    volumes:
      - ./config/prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'