replicaCount: 2
image:
  repository: FROM ghcr.io/shabz3/infra-coingecko:main
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 30000
resources:
  limits:
    cpu: "250m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"
ingress:
  enabled: false