name: Publish-helm-chart

on:
  workflow_run:
    workflows: ["Build-test-push"]
    types:
      - completed

jobs:
  publish-helm-chart:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: |
          helm registry login ghcr.io \
            -u ${{ github.actor }} \
            -p ${{ secrets.GITHUB_TOKEN }}

      - name: Package Helm chart
        run: |
          helm lint chart/
          helm package chart/

      - name: Push Helm chart
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pwd
          ls -LR
          helm push ./${{ github.event.repository.name }}-*.tgz oci://ghcr.io/${{ github.repository_owner }}/infra-coingecko-charts